#
# @Todo define a specific node
# oc create sa caius
# NS=$(oc project -q)
# oc policy add-role-to-user view system:serviceaccount:${NS}:caius
#
---
apiVersion: batch/v1
kind: Job
metadata:
  name: gcvp-caius
  labels:
    app: gcvp-caius
    io.shyrka.erebus.tooling-info/role: audit
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 4
  template:
    spec:
      metadata:
      name: gcvp-caiuspupus
      labels:
        app: gcvp-caiuspupus
      restartPolicy: Never
      serviceAccount: caius
      containers:
        - name: gcvp
          image: 172.30.1.1:5000/infra-anacreon-dev-ags-fr/gcvp:0.0.3
          imagePullPolicy: Always
          command: ["java"]
          args: ["-jar","gcvp-0.0.3.jar","-caius","-caiusNS",$(KUBERNETES_NAMESPACE),"-o", "-caiusLabels" , $(DEPLOYMENT_LABEL) ]
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace           
            - name: DEPLOYMENT_LABEL
              value: 'deploymentconfig=testing'
          resources:
            limits:
              memory: 1Gi
              cpu: 500m
            requests:
              memory: 100Mi
              cpu: 500m